"""Structural constants. User-tunable behavior belongs in defaults.toml."""

CONFIG_SCHEMA_VERSION = "1.0"
DATABASE_SCHEMA_VERSION = 2
MEMORY_SCHEMA_VERSION = "1.1"
APPLICATION_VERSION = "0.2.0"

MINIMUM_RESULT_LIMIT = 1
UNIT_INTERVAL_MIN = 0.0
UNIT_INTERVAL_MAX = 1.0
SIGNED_INTERVAL_MIN = -1.0
SIGNED_INTERVAL_MAX = 1.0
WEIGHT_TARGET = 1.0
WEIGHT_TOLERANCE = 1e-9
EMPTY_SCORE = 0.0
PERFECT_SCORE = 1.0
HALF_LIFE_BASE = 0.5

SECONDS_PER_HOUR = 60 * 60
HOURS_PER_DAY = 24
SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY
DAYS_PER_WEEK = 7
MONTHS_PER_YEAR = 12
CALENDAR_FIRST_DAY = 1
CALENDAR_FIRST_MONTH = 1
RELATIVE_YESTERDAY_DAYS = 1
RELATIVE_DAY_BEFORE_YESTERDAY_DAYS = 2
SHA256_HEX_LENGTH = 64
STABLE_KEY_DIGEST_PREFIX_LENGTH = 16
FLOAT32_BYTES = 4
AMBIGUITY_MINIMUM_CANDIDATES = 2

DEFAULT_CONFIG_RESOURCE = "defaults.toml"
DEFAULT_ENCODING = "utf-8"
CONFIG_ENV_NAME = "COMPANION_MEMORYOS_CONFIG"
DATA_HOME_ENV_NAME = "COMPANION_MEMORYOS_HOME"
SQLITE_INTEGRITY_OK = "ok"
